services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    container_name: iot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: iot-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  mongo_data:
